/**
 *
 * @returns response json to mimic api call for testing purposes
 */

const Response = () => [
  { name: "12th st. oakland city center", abbr: "12th" },
  { name: "16th st. mission", abbr: "16th" },
  { name: "19th st. oakland", abbr: "19th" },
  { name: "24th st. mission", abbr: "24th" },
  { name: "antioch", abbr: "antc" },
  { name: "ashby", abbr: "ashb" },
  { name: "balboa park", abbr: "balb" },
  { name: "bay fair", abbr: "bayf" },
  { name: "berryessa/north san jose", abbr: "bery" },
  { name: "castro valley", abbr: "cast" },
  { name: "civic center/un plaza", abbr: "civc" },
  { name: "coliseum", abbr: "cols" },
  { name: "colma", abbr: "colm" },
  { name: "concord", abbr: "conc" },
  { name: "daly city", abbr: "daly" },
  { name: "downtown berkeley", abbr: "dbrk" },
  { name: "dublin/pleasanton", abbr: "dubl" },
  { name: "el cerrito del norte", abbr: "deln" },
  { name: "el cerrito plaza", abbr: "plza" },
  { name: "embarcadero", abbr: "embr" },
  { name: "fremont", abbr: "frmt" },
  { name: "fruitvale", abbr: "ftvl" },
  { name: "glen park", abbr: "glen" },
  { name: "hayward", abbr: "hayw" },
  { name: "lafayette", abbr: "lafy" },
  { name: "lake merritt", abbr: "lake" },
  { name: "macarthur", abbr: "mcar" },
  { name: "millbrae", abbr: "mlbr" },
  { name: "milpitas", abbr: "mlpt" },
  { name: "montgomery st.", abbr: "mont" },
  { name: "north berkeley", abbr: "nbrk" },
  { name: "north concord/martinez", abbr: "ncon" },
  { name: "oakland international airport", abbr: "oakl" },
  { name: "orinda", abbr: "orin" },
  { name: "pittsburg/bay point", abbr: "pitt" },
  { name: "pittsburg center", abbr: "pctr" },
  { name: "pleasant hill/contra costa centre", abbr: "phil" },
  { name: "powell st.", abbr: "powl" },
  { name: "richmond", abbr: "rich" },
  { name: "rockridge", abbr: "rock" },
  { name: "san bruno", abbr: "sbrn" },
  { name: "san francisco international airport", abbr: "sfia" },
  { name: "san leandro", abbr: "sanl" },
  { name: "south hayward", abbr: "shay" },
  { name: "south san francisco", abbr: "ssan" },
  { name: "union city", abbr: "ucty" },
  { name: "walnut creek", abbr: "wcrk" },
  { name: "warm springs/south fremont", abbr: "warm" },
  { name: "west dublin/pleasanton", abbr: "wdub" },
  { name: "west oakland", abbr: "woak" }
];

export default Response;
